"""
Django settings for webproject project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-feji)n9=4&&)(b36qeo&yve1aufu78^$o5#8uec+&8_1p&ul9)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允許存取的IP
ALLOWED_HOSTS = []


# Application definition
# 只要將你創建的 apps 放進來這裡，告訴 Django apps應用程序處於活動狀態
# 配合著 migrate，則它就會去監督該 apps 的 models(就是資料庫的型態)
INSTALLED_APPS = [
    'welcome',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webproject.urls'

import os
TEMPLATES = [  #  Django 預設去找 TEMPLATES 的設定
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],  # DIRS : 這是請Django額外搜尋TEMPLATES的目錄 # [] -> [BASE_DIR+"/templates"]
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 設定完成，需要輸入
# > python manage.py migrate
# 將Django Model中的資料模型同步至PostgreSQL資料庫中
# 完成後，即可看到Django專案同步過來的資料表

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
        'NAME': '',  #資料庫名稱
        'USER': '',   #資料庫帳號
        'PASSWORD': '',  #資料庫密碼
        'HOST': '',  #Server(伺服器)位址(IP)
        'PORT': '',       #PostgreSQL Port號
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
#        'NAME': 'house_test',  #資料庫名稱
#        'USER': 'postgres',   #資料庫帳號
#        'PASSWORD': 'sunny123123',  #資料庫密碼
#        'HOST': 'localhost',  #Server(伺服器)位址(IP)
#        'PORT': '5432',       #PostgreSQL Port號
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/statics/'
STATICFILES_DIRS = [
  os.path.join(BASE_DIR, "statics"),
]

# 上傳圖片路徑
MEDIA_ROOT = os.path.join(BASE_DIR, 'statics', 'uploadFile')
MEDIA_URL = '/uploadFile/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL 登入後跳轉的頁面預設值/ LOGIN_URL:請求登入跳轉的頁面預設值
#LOGIN_REDIRECT_URL = '/welcome/home/'
#LOGIN_URL = '/welcome/login/'

# 指定要驗證的使用者模型 / 在自訂使用者模型的情況下，需要指定自訂的驗證後端
AUTH_USER_MODEL = 'welcome.User_Account'
AUTHENTICATION_BACKENDS = [
    'welcome.backends.EmailBackend',
]

# 傳檔要改路徑(刪掉不行)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GDAL_LIBRARY_PATH = r'C:\Users\user\anaconda3\envs\django\Library\bin\gdal.dll'
os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH
