# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'houseUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(60, 400, 121, 121))
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton1.setMouseTracking(False)
        self.pushButton1.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(390, 400, 121, 121))
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton2.setStyleSheet("background-color: rgb(255, 171, 69);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.pushButton2.setAutoDefault(False)
        self.pushButton2.setObjectName("pushButton2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 176, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 140, 41, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 140, 81, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 290, 81, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 290, 81, 25))
        self.label_5.setObjectName("label_5")
        self.textBrowser3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser3.setGeometry(QtCore.QRect(80, 40, 471, 121))
        self.textBrowser3.setStyleSheet("background-color: rgb(255, 220, 225);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.textBrowser3.setObjectName("textBrowser3")
        self.toolButton3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton3.setGeometry(QtCore.QRect(120, 50, 81, 81))
        self.toolButton3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton3.setStyleSheet("background-image: url(:/newPrefix/雅房 (1).png);")
        self.toolButton3.setCheckable(True)
        self.toolButton3.setAutoRaise(True)
        self.toolButton3.setObjectName("toolButton3")
        self.toolButton4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton4.setGeometry(QtCore.QRect(370, 50, 81, 81))
        self.toolButton4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton4.setStyleSheet("background-image: url(:/newPrefix/分租套房 (1).png);")
        self.toolButton4.setCheckable(True)
        self.toolButton4.setAutoRaise(True)
        self.toolButton4.setObjectName("toolButton4")
        self.toolButton6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton6.setGeometry(QtCore.QRect(370, 200, 81, 81))
        self.toolButton6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton6.setStyleSheet("background-image: url(:/newPrefix/整層住家 (1).png);")
        self.toolButton6.setCheckable(True)
        self.toolButton6.setAutoRaise(True)
        self.toolButton6.setObjectName("toolButton6")
        self.toolButton5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton5.setGeometry(QtCore.QRect(120, 200, 81, 81))
        self.toolButton5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton5.setStyleSheet("background-image: url(:/newPrefix/獨立套房 (1).png);")
        self.toolButton5.setCheckable(True)
        self.toolButton5.setAutoRaise(True)
        self.toolButton5.setObjectName("toolButton5")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(130, 160, 331, 221))
        self.groupBox2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0.165, stop:0.564972 rgba(86, 169, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.comboBox2 = QtWidgets.QComboBox(self.groupBox2)
        self.comboBox2.setGeometry(QtCore.QRect(70, 80, 181, 31))
        self.comboBox2.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.labelChoose2 = QtWidgets.QLabel(self.groupBox2)
        self.labelChoose2.setGeometry(QtCore.QRect(20, 40, 171, 21))
        self.labelChoose2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelChoose2.setObjectName("labelChoose2")
        self.OKButton2 = QtWidgets.QPushButton(self.groupBox2)
        self.OKButton2.setEnabled(False)
        self.OKButton2.setGeometry(QtCore.QRect(80, 180, 75, 23))
        self.OKButton2.setObjectName("OKButton2")
        self.CancelButton2 = QtWidgets.QPushButton(self.groupBox2)
        self.CancelButton2.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.CancelButton2.setObjectName("CancelButton2")
        self.labelexp3 = QtWidgets.QLabel(self.centralwidget)
        self.labelexp3.setGeometry(QtCore.QRect(210, 50, 311, 101))
        self.labelexp3.setObjectName("labelexp3")
        self.labelexp4 = QtWidgets.QLabel(self.centralwidget)
        self.labelexp4.setGeometry(QtCore.QRect(70, 40, 261, 61))
        self.labelexp4.setObjectName("labelexp4")
        self.textBrowser4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser4.setGeometry(QtCore.QRect(30, 40, 471, 121))
        self.textBrowser4.setStyleSheet("background-color: rgb(213, 251, 255);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.textBrowser4.setObjectName("textBrowser4")
        self.textBrowser5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser5.setGeometry(QtCore.QRect(70, 190, 471, 121))
        self.textBrowser5.setStyleSheet("background-color: rgb(217, 255, 212);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.textBrowser5.setObjectName("textBrowser5")
        self.labelexp5 = QtWidgets.QLabel(self.centralwidget)
        self.labelexp5.setGeometry(QtCore.QRect(220, 200, 271, 81))
        self.labelexp5.setObjectName("labelexp5")
        self.textBrowser6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser6.setGeometry(QtCore.QRect(30, 190, 471, 121))
        self.textBrowser6.setStyleSheet("background-color: rgb(236, 205, 255);\n"
"font: 12pt \"標楷體\";\n"
"border-radius:60px;")
        self.textBrowser6.setObjectName("textBrowser6")
        self.labelexp6 = QtWidgets.QLabel(self.centralwidget)
        self.labelexp6.setGeometry(QtCore.QRect(70, 190, 301, 121))
        self.labelexp6.setObjectName("labelexp6")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(140, 160, 331, 221))
        self.groupBox1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0.165, stop:0.564972 rgba(86, 169, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.comboBox1 = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox1.setGeometry(QtCore.QRect(70, 80, 181, 31))
        self.comboBox1.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.labelChoose1 = QtWidgets.QLabel(self.groupBox1)
        self.labelChoose1.setGeometry(QtCore.QRect(20, 40, 171, 21))
        self.labelChoose1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelChoose1.setObjectName("labelChoose1")
        self.OKButton = QtWidgets.QPushButton(self.groupBox1)
        self.OKButton.setEnabled(False)
        self.OKButton.setGeometry(QtCore.QRect(80, 180, 75, 23))
        self.OKButton.setObjectName("OKButton")
        self.CancelButton = QtWidgets.QPushButton(self.groupBox1)
        self.CancelButton.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.label.raise_()
        self.groupBox2.raise_()
        self.groupBox1.raise_()
        self.textBrowser3.raise_()
        self.label_2.raise_()
        self.labelexp3.raise_()
        self.toolButton3.raise_()
        self.textBrowser4.raise_()
        self.labelexp4.raise_()
        self.label_3.raise_()
        self.toolButton4.raise_()
        self.textBrowser5.raise_()
        self.label_4.raise_()
        self.labelexp5.raise_()
        self.toolButton5.raise_()
        self.textBrowser6.raise_()
        self.label_5.raise_()
        self.labelexp6.raise_()
        self.toolButton6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton1.setText(_translate("MainWindow", "分析各縣市\n"
"平均月租金"))
        self.pushButton2.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton2.setText(_translate("MainWindow", "分析各房型\n"
"平均月租金"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">房型格局怎麼分？</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">雅房</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">分租套房</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">獨立套房</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">整層住家</span></p></body></html>"))
        self.textBrowser3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'標楷體\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolButton3.setText(_translate("MainWindow", "..."))
        self.toolButton4.setText(_translate("MainWindow", "..."))
        self.toolButton6.setText(_translate("MainWindow", "..."))
        self.toolButton5.setText(_translate("MainWindow", "..."))
        self.comboBox2.setItemText(0, _translate("MainWindow", "請選擇..."))
        self.comboBox2.setItemText(1, _translate("MainWindow", "-----北部-----"))
        self.comboBox2.setItemText(2, _translate("MainWindow", "新北市"))
        self.comboBox2.setItemText(3, _translate("MainWindow", "臺北市"))
        self.comboBox2.setItemText(4, _translate("MainWindow", "基隆市"))
        self.comboBox2.setItemText(5, _translate("MainWindow", "宜蘭縣"))
        self.comboBox2.setItemText(6, _translate("MainWindow", "桃園市"))
        self.comboBox2.setItemText(7, _translate("MainWindow", "新竹市"))
        self.comboBox2.setItemText(8, _translate("MainWindow", "新竹縣"))
        self.comboBox2.setItemText(9, _translate("MainWindow", "-----中部-----"))
        self.comboBox2.setItemText(10, _translate("MainWindow", "苗栗縣"))
        self.comboBox2.setItemText(11, _translate("MainWindow", "臺中市"))
        self.comboBox2.setItemText(12, _translate("MainWindow", "彰化縣"))
        self.comboBox2.setItemText(13, _translate("MainWindow", "雲林縣"))
        self.comboBox2.setItemText(14, _translate("MainWindow", "南投縣"))
        self.comboBox2.setItemText(15, _translate("MainWindow", "-----南部-----"))
        self.comboBox2.setItemText(16, _translate("MainWindow", "嘉義市"))
        self.comboBox2.setItemText(17, _translate("MainWindow", "嘉義縣"))
        self.comboBox2.setItemText(18, _translate("MainWindow", "臺南市"))
        self.comboBox2.setItemText(19, _translate("MainWindow", "高雄市"))
        self.comboBox2.setItemText(20, _translate("MainWindow", "屏東縣"))
        self.comboBox2.setItemText(21, _translate("MainWindow", "澎湖縣"))
        self.comboBox2.setItemText(22, _translate("MainWindow", "-----東部-----"))
        self.comboBox2.setItemText(23, _translate("MainWindow", "臺東縣"))
        self.comboBox2.setItemText(24, _translate("MainWindow", "花蓮縣"))
        self.comboBox2.setItemText(25, _translate("MainWindow", "-----外島-----"))
        self.comboBox2.setItemText(26, _translate("MainWindow", "連江縣"))
        self.comboBox2.setItemText(27, _translate("MainWindow", "金門縣"))
        self.labelChoose2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">選擇想看的縣市？</span></p></body></html>"))
        self.OKButton2.setText(_translate("MainWindow", "OK"))
        self.CancelButton2.setText(_translate("MainWindow", "Cancel"))
        self.labelexp3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">大多提供給單身人士居住，但不同於套房，<br/>套房為擁有獨立的衛浴設備（少數有簡易廚<br/>房可供烹飪食物，甚至有衣帽間、小客廳、<br/>會議廳、書房等），雅房則需要與他人共享<br/>衛浴設備及廚房。</span></p></body></html>"))
        self.labelexp4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">分租套房，是指一個人一個房間，<br/>房間內附有獨立衛浴的房間。</span></p></body></html>"))
        self.textBrowser4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'標楷體\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'標楷體\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelexp5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">獨立套房：就是縮小版的整層住家，<br/>擁有獨立產權（所以才可以買賣）、<br/>獨立門牌和自己的電號，坪數也會稍<br/>大一點</span></p></body></html>"))
        self.textBrowser6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'標楷體\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelexp6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">整層住家有點像是放大版的獨立套房，<br/>但格局更多樣，最常見的是兩到三房的<br/>型態，也有較罕見的四到五房等。 整層<br/>住家除了臥房和衛浴外，會有廚房、客<br/>廳、餐廳和前後陽台等空間，能享受更<br/>好的生活品質。</span></p></body></html>"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "請選擇..."))
        self.comboBox1.setItemText(1, _translate("MainWindow", "雅房"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "分租套房"))
        self.comboBox1.setItemText(3, _translate("MainWindow", "獨立套房"))
        self.comboBox1.setItemText(4, _translate("MainWindow", "整層住家2房"))
        self.comboBox1.setItemText(5, _translate("MainWindow", "整層住家3房"))
        self.comboBox1.setItemText(6, _translate("MainWindow", "整層住家4房"))
        self.comboBox1.setItemText(7, _translate("MainWindow", "整層住家5房"))
        self.comboBox1.setItemText(8, _translate("MainWindow", "整層住家6房"))
        self.comboBox1.setItemText(9, _translate("MainWindow", "整層住家7房"))
        self.comboBox1.setItemText(10, _translate("MainWindow", "整層住家8房"))
        self.comboBox1.setItemText(11, _translate("MainWindow", "整層住家9房"))
        self.labelChoose1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">選擇想看的房型？</span></p></body></html>"))
        self.OKButton.setText(_translate("MainWindow", "OK"))
        self.CancelButton.setText(_translate("MainWindow", "Cancel"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

