# Generated by Django 4.1.7 on 2023-11-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField()),
                ('telephone', models.TextField()),
                ('gender', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyHouse591House',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('建物類型', models.CharField(db_column='建物類型', max_length=8)),
                ('地址', models.CharField(db_column='地址', max_length=32)),
                ('樓層', models.IntegerField(db_column='樓層')),
                ('格局_房數', models.IntegerField(db_column='格局_房數')),
                ('格局_衛浴數', models.IntegerField(db_column='格局_衛浴數')),
                ('格局_廚房數', models.IntegerField(db_column='格局_廚房數')),
                ('格局_客廳數', models.IntegerField(db_column='格局_客廳數')),
                ('格局_陽台數', models.IntegerField(db_column='格局_陽台數')),
                ('插座數', models.IntegerField(blank=True, db_column='插座數', null=True)),
                ('坪數', models.IntegerField(db_column='坪數')),
                ('提供家具_桌子', models.BooleanField(db_column='提供家具_桌子？')),
                ('提供家具_椅子', models.BooleanField(db_column='提供家具_椅子？')),
                ('提供家具_沙發', models.BooleanField(db_column='提供家具_沙發？')),
                ('提供家具_衣櫃', models.BooleanField(db_column='提供家具_衣櫃？')),
                ('提供家具_收納櫃', models.BooleanField(db_column='提供家具_收納櫃？')),
                ('提供家具_床', models.BooleanField(db_column='提供家具_床？')),
                ('提供設備_洗衣機', models.BooleanField(db_column='提供設備_洗衣機？')),
                ('洗衣機類型', models.CharField(blank=True, db_column='洗衣機類型', max_length=2, null=True)),
                ('提供設備_烘衣機', models.BooleanField(db_column='提供設備_烘衣機？')),
                ('烘衣機類型', models.CharField(blank=True, db_column='烘衣機類型', max_length=2, null=True)),
                ('提供設備_冰箱', models.BooleanField(db_column='提供設備_冰箱？')),
                ('冰箱類型', models.CharField(blank=True, db_column='冰箱類型', max_length=2, null=True)),
                ('提供設備_冷氣', models.BooleanField(db_column='提供設備_冷氣？')),
                ('冷氣類型', models.CharField(blank=True, db_column='冷氣類型', max_length=2, null=True)),
                ('提供設備_室內窗', models.BooleanField(db_column='提供設備_室內窗？')),
                ('室內窗類型', models.CharField(blank=True, db_column='室內窗類型', max_length=2, null=True)),
                ('提供設備_電梯', models.BooleanField(db_column='提供設備_電梯？')),
                ('提供設備_熱水器', models.BooleanField(db_column='提供設備_熱水器？')),
                ('提供設備_天然瓦斯', models.BooleanField(db_column='提供設備_天然瓦斯？')),
                ('提供設備_電視', models.BooleanField(db_column='提供設備_電視？')),
                ('提供設備_第四台', models.BooleanField(db_column='提供設備_第四台？')),
                ('提供設備_網路', models.BooleanField(db_column='提供設備_網路？')),
                ('價格', models.IntegerField(db_column='價格')),
                ('押金', models.IntegerField(db_column='押金')),
                ('電費類型', models.CharField(db_column='電費類型', max_length=2)),
                ('自訂電費價格', models.IntegerField(blank=True, db_column='自訂電費價格', null=True)),
                ('水費類型', models.CharField(db_column='水費類型', max_length=2)),
                ('自訂水費價格', models.IntegerField(blank=True, db_column='自訂水費價格', null=True)),
                ('提供停車位', models.BooleanField(db_column='提供停車位？')),
                ('停車位費用', models.IntegerField(blank=True, db_column='停車位費用', null=True)),
                ('需要管理費', models.BooleanField(db_column='需要管理費？')),
                ('管理費費用', models.IntegerField(blank=True, db_column='管理費費用', null=True)),
                ('廣告標題', models.CharField(db_column='廣告標題', max_length=32)),
                ('最短租期', models.IntegerField(db_column='最短租期')),
                ('最短租期單位', models.CharField(db_column='最短租期單位', max_length=1)),
                ('刊登者類型', models.CharField(db_column='刊登者類型', max_length=3)),
                ('有性別限制', models.BooleanField(db_column='有性別限制？')),
                ('性別限制', models.CharField(blank=True, db_column='性別限制', max_length=2, null=True)),
                ('有身分限制', models.BooleanField(db_column='有身分限制？')),
                ('身分限制_學生', models.BooleanField(db_column='身分限制_學生？')),
                ('身分限制_上班族', models.BooleanField(db_column='身分限制_上班族？')),
                ('身分限制_家庭', models.BooleanField(db_column='身分限制_家庭？')),
                ('有寵物限制', models.BooleanField(db_column='有寵物限制？')),
                ('是否可伙', models.BooleanField(db_column='是否可伙？')),
                ('有產權登記', models.BooleanField(db_column='有產權登記？')),
                ('來源平台', models.CharField(db_column='來源平台', max_length=8)),
                ('圖片路徑', models.CharField(blank=True, db_column='圖片路徑', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓氏', models.CharField(blank=True, max_length=32, null=True)),
                ('名字', models.CharField(blank=True, max_length=32, null=True)),
                ('電話', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('房屋編號', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.myhouse591house')),
            ],
        ),
    ]
