# Generated by Django 4.1.7 on 2023-11-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhouse591house',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userhouse',
            options={'managed': False},
        ),
    ]
