# Generated by Django 4.1.7 on 2023-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_myhouse591house_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myhouse591house',
            table='myhouse_591house',
        ),
        migrations.AlterModelTable(
            name='userhouse',
            table='user_house',
        ),
    ]
