# Generated by Django 4.1.7 on 2023-11-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_myhouse591house_table_alter_userhouse_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user_account',
            table='user_account',
        ),
    ]
