# Generated by Django 4.1.7 on 2023-11-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_user_account_options_alter_user_account_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={},
        ),
        migrations.AlterModelTable(
            name='user_account',
            table=None,
        ),
    ]
