# Generated by Django 4.1.7 on 2023-12-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_user_account_options_alter_user_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
