# Generated by Django 4.1.7 on 2023-12-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_rename_name_user_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhouse591house',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userhouse',
            options={'managed': True},
        ),
    ]
