# Generated by Django 4.1.7 on 2023-12-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_alter_myhouse591house_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhouse591house',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userhouse',
            options={'managed': False},
        ),
    ]
