# Generated by Django 4.1.7 on 2023-12-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_alter_myhouse591house_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('合租人姓名', models.TextField()),
                ('合租人電話', models.IntegerField()),
                ('合租人信箱', models.TextField()),
            ],
            options={
                'db_table': 'grouptenant',
                'managed': False,
            },
        ),
    ]
