# Generated by Django 4.1.7 on 2023-12-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_grouptenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptenant',
            options={'managed': True},
        ),
    ]
