# Generated by Django 4.1.7 on 2023-12-12 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_alter_grouptenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptenant',
            name='houseid',
            field=models.ForeignKey(db_column='houseID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.myhouse591house'),
        ),
        migrations.AddField(
            model_name='grouptenant',
            name='userid',
            field=models.ForeignKey(db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptenant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='grouptenant',
            constraint=models.UniqueConstraint(fields=('houseid', 'userid'), name='houseID_userID_PK'),
        ),
    ]
