# Generated by Django 4.1.7 on 2023-12-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_grouptenant_houseid_grouptenant_userid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grouptenant',
            table=None,
        ),
    ]
