# Generated by Django 4.1.7 on 2023-12-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_alter_grouptenant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grouptenant',
            table='grouptenant',
        ),
    ]
