# Generated by Django 4.1.7 on 2023-12-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_alter_grouptenant_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptenant',
            options={'managed': False},
        ),
    ]
